# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#9ccfd8" }

# Hovered
hovered = { fg = "#e0def4", bg = "#26233a" }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#f6c177", italic = true }
find_position = { fg = "#eb6f92", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#9ccfd8", bg = "#9ccfd8" }
marker_copied = { fg = "#f6c177", bg = "#f6c177" }
marker_cut = { fg = "#B4637A", bg = "#B4637A" }

# Tab
tab_width = 1

# Border
border_symbol = "│"
border_style = { fg = "#524f67" }

# Highlighting
syntect_theme = "~/.config/yazi/rose-pine.tmTheme"

# : }}}

# : Tabs {{{

[tabs]
active = { fg = "#26233a", bg = "#ebbcba" }
inactive = { fg = "#ebbcba", bg = "#26233a" }
sep_inner = { open = " ", close = " " }
sep_outer = { open = " ", close = " " }
# }}}

# : Status {{{

[status]
# Separators
sep_left = { open = "  ", close = " " }
sep_right = { open = " ", close = "  " }

# Progress
progress_label = { fg = "#e0def4", bold = true }
progress_normal = { fg = "#191724", bg = "#2A273F" }
progress_error = { fg = "#B4637A", bg = "#2A273F" }

# Permissions
perm_type = { fg = "#31748f" }
perm_read = { fg = "#f6c177" }
perm_write = { fg = "#B4637A" }
perm_exec = { fg = "#9ccfd8" }
perm_sep = { fg = "#524f67" }

# : }}}

# : Mode {{{
[mode]
normal_main = { fg = "#191724", bg = "#ebbcba", bold = true }
normal_alt = { fg = "#191724", bg = "#ebbcba", bold = true }
select_main = { fg = "#e0def4", bg = "#9ccfd8", bold = true }
select_alt = { fg = "#e0def4", bg = "#9ccfd8", bold = true }
unset_main = { fg = "#e0def4", bg = "#b4637a", bold = true }
unset_alt = { fg = "#e0def4", bg = "#b4637a", bold = true }
# : }}}

# : Input {{{

[input]
border = { fg = "#524f67" }
title = {}
value = {}
selected = { reversed = true }

# : }}}


# : Pick {{{

[pick]
border = { fg = "#524f67" }
active = { fg = "#eb6f92" }
inactive = {}
# }}} 


# : Tasks {{{

[tasks]
border = { fg = "#524f67" }
title = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask = { bg = "#313244" }
cand = { fg = "#9ccfd8" }
rest = { fg = "#9399b2" }
desc = { fg = "#eb6f92" }
separator = "  "
separator_style = { fg = "#585b70" }

# : }}}


# : Help {{{

[help]
on = { fg = "#eb6f92" }
exec = { fg = "#9ccfd8" }
desc = { fg = "#9399b2" }
hovered = { bg = "#585b70", bold = true }
footer = { fg = "#2A273F", bg = "#e0def4" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#9ccfd8" },

    # Videos
    { mime = "video/*", fg = "#f6c177" },
    { mime = "audio/*", fg = "#f6c177" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#eb6f92" },

    # Fallback
    { name = "*", fg = "#e0def4" },
    { name = "*/", fg = "#524f67" },
]

# : }}}
